language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: EbDtOmplzV4abvJpF9XNzHs6xPpnJNkMErYzo0+TDgb/YzZDCZoWgqe3tQ/7tyTh+azu+7rf61KwxZcIjGwZLJOZuVsUoODaiedQm7PPWj5xut6lRQdeurMQVn7PZnjf3oN3RowyULjohp1Tu5JfZVx4lPSU4fkXDVH3OwvQD4PGKdJaXTXpJhtRO/xnOlm+wh50uwLqYpjBhE4TQkffAvwpxP1Z2gV1s3xiNPZo5SHRFCCOhiVMQoNTOQR4H5S3ogzxkz/j6WQWF3FSTbs8/qjYU6wNRxmnZullEB05klOCjJZ8f6kfPkatXlOFZ3cnbs5LR1oyBvTIN6xiaoEoxxbCwL/qu/D8UxnAkVC6A+LI93le0ZKP9xJTUd0WKTWwzvmmc4MSw9rVzIljA3AM2QgYrKPLm4RNCclJxml9ARpyhJmsDgYP6DIgZL8EGx2qq0Nn0SpKw4Kyxdh+DQ2lU9tdoi4gHLW3iVXKDNK0YQD64zuqzY2yAworHM9eYjeiXC1bTrWWRkEbQmv06taHg1QCiYNp4VRjv9PcaXGAnxOQjrjReUKFRBoKA6nKRLwgYnhQmBK4UrvenIrMcucKtYgdnbfVOhpSFDOtSxX3mjASN0dSLUJDlUu7Itt2zlooZ/vhtfYrxPhLUH29EbnLKBg1RljfGhZqieRfI1a80K8=
  app: warm-refuge-51520
  on:
    repo: HanBitPix/node-shopping-list-integration-tests
